import random

fortunes = [
    "It is certain.",
    "It is decidedly so.",
    "Without a doubt.",
    "Yes, definitely.",
    "You may rely on it.",
    "As I see it, yes.",
    "Most likely.",
    "The outlook is good.",
    "Yes.",
    "The stars point to yes.",
    "The fortune is hazy... ask me later.",
    "I cannot tell you now.",
    "It is impossible to predict.",
    "I don't believe so.",
    "The stars point to no.",
    "I am doubtful.",
    "How could it be, dear?",
    "Psh.",
    "Sadly not, my sweet.",
    "The vibes are off.",
    "Ask again later. I’m tired and need a beverage.",
    "Ugh, this again? Ask later, you bore me.",
    "Not in a million, million years.",
    "Yes, yes, yes. A million times, yes.",
    "The butterflies don’t agree.",
    "The butterflies are in your favor.",
    "The wings flap for you, my dear.",
    "Oh, my dearest, I think not.",
    "Oh, my dearest, I think most certainly so.",
    "Oh, honey…no.",
    "Oh, sweetie…",
    "Oh, my love…",
    "Oh, my lovely little flower.",
    "Oh, my sweet little knight.",
    "There are shades of red in your eyes, love. I don’t think so.",
    "There are shades of blue in your heart, dear. I believe it’s true.",
    "The colors favor you.",
    "The colors are bashful. Try a different question.",
    "The colors hide from you.",
    "The pale covers this question. It’s best I don’t answer now.",
    "I refuse to answer.",
    "There is darkness here. Flee.",
    "The brightest light shines on you.",
    "My pretty, pretty thing, don’t bother yourself with such trivialities.",
    "lmao. lol.",
    "There’s not a chance. I’m sorry. I can’t believe you’d even ask.",
    "Oh yes, sweetie. You don’t need to ask.",
    "The question doesn’t require an answer.",
    "As the tide laps the shore, I will always answer yes.",
    "The fire will not save you. Don’t ask again.",
    "Oh, honey…yes.",
    "Oh, honey…most definitely not.",
    "Oh, honey…most certainly.",
    "Oh, sweetie…yes.",
    "Oh, sweetie…most definitely not.",
    "Oh, sweetie…most certainly.",
    "Oh, my love…yes.",
    "Oh, my love…no.",
    "Oh, my love…most certainly not.",
    "Oh, my love…most certainly.",
    "Oh, my lovely little flower, no.",
    "Oh, my lovely little flower, yes.",
    "Oh, my lovely little flower, most certainly.",
    "Oh, my lovely little flower, most certainly not.",
    "The question bores me, so no.",
    "Ooo, I love this question, dear. Yes, yes, yes.",
    "I can’t find the energy to care at this moment. Try again later.",
    "I hope this doesn’t offend you, but no.",
    "I believe you will find the answer on your own.",
    "Oh, my sweet little knight, no.",
    "Oh, my sweet little knight, most certainly.",
    "Oh, my sweet little knight, it is known.",
    "We can only decide through a duel. Roll a d6 and try to beat my 5. That will answer your question.",
    "Ask someone else. Someone you love.",
    "Ask your rival. They know the truth.",
]

incorrect_responses = [
    "What are you asking me?",
    "Speak clearly.",
    "I can't hear you when you mumble, dear.",
    "What’s that?",
    "You must try harder if you want an answer.",
    "Go to the garden and bring me a flower before talking to me.",
    "Don’t chip away at my time with frivolities. Try again.",
    "What’s that? You’ve insulted me with your ignorance.",
    "Huh?",
    "Ugh, please address me correctly, my sweet. ",
    "Ugh, please address me correctly, flower. ",
    "Your question is lost on me. Try again.",
]

responses = [
    "Let me draw a card from my deck.",
    "Let’s see what the cards say.",
    "Let’s draw a card and find out.",
    "Let’s see what the cards say together.",
]

tarot = {
    "The Maiden": "Your day will require comfort and careful choices. Be soft and gentle with yourself and look for those things that bring you safety. Take my hug and be on your way.",
    "Her Caring Hands": "Today is about touching, feeling, haunting the things around you. Be present with them in ways that can be quantified. Eat from them and let yourself be eaten from.",
    "The Ghost": "Careful of nostalgia today. Things from the past may bubble up and taunt you. Welcome them at your own risk.",
    "The Wishing Curse": "Your naivety can make you bite off more than you can chew. Be slow and deliberate with your day. These hours may take longer to digest.",
    "The Writ": "Today is a day already written in history. Do not fret over what happens. Let it come and wash over you. It is merely a single day.",
    "The Phoenix": "There’s a sweetness in suffering. Recollect all the bits of you that have chipped off and give them burials of kindness. You are you and everything you’ve shed.",
    "The Bind": "Let the things go that want to leave. Like birds. Careful of the cages trying to close on you. Today is not the day to make such pivotal decisions.",
    "The Bridge": "Blessings on your journey, whether a distance of miles or of hearts. Someone new might be what you need to change your perspective.",
    "His Bones": "Careful of the rain today. Be strong. You are the wall that stands longer than all else.",
    "Burn": "A day of destruction. Beautiful destruction. Let it all fall away if need be. Take a bat to the vase of your complacency. Find joy in decimation.",
    "Her Blood": "Focus on today. Let your mind rest and heal your wounds (I know you have them). Shh, seriously. Chill <3.",
    "The Twins": "Don’t get lost in your mistakes today for they may resurface. Be cognizant of the things you chose not to do and remember why you chose not to do them.",
    "The Lovers": "Be wary of swirling emotions today. Whirlwinds afoot. Closeness and affection can ease the mind. Don’t get tangled.",
    "Map of Gore": "Something is happening and sooner than you’d like. It’s okay. Let it hurt. Let the emotions be unfettered by your explanations. Let them out.",
    "Hunt": "Your dreams are important because you hope. Don’t fret if they don’t turn out. Just let them exist and take solace in their life.",
    "Her Spine": "A difficult confrontation of the mind, body, or spirit. Stand up for yourself in these times. Fight for the space you need.",
    "Field of Swords": "A day of hope and betterment. The old things may become new once again. Let it all try, at the very least.",
    "Punishment": "Stay sheltered today. The world and its pressures are fraught. Be careful of outside forces on your journey.",
    "The Black Moon": "Today is a day of darkness. But that is okay. In the darkness you can find yourself again. Bring a torch.",
    "The Moon": "A death of some kind. A rebirth of another. This is a day of major change, whether you spark it or you simply react. It will be beautiful.",
    "The Sun": "Today is an example of eternity. The cycle of life. Recycle, regrow, repurpose. Let yourself be part of this cycle. Let nature be your neighbor.",
}

tarot_names = [
    "The Maiden",
    "Her Caring Hands",
    "The Ghost",
    "The Wishing Curse",
    "The Writ",
    "The Phoenix",
    "The Bind",
    "The Bridge",
    "His Bones",
    "Burn",
    "Her Blood",
    "The Twins",
    "The Lovers",
    "Map of Gore",
    "Hunt",
    "Her Spine",
    "Field of Swords",
    "Punishment",
    "The Black Moon",
    "The Moon",
    "The Sun",
]


def eightball():
    num = random.randint(0, len(fortunes) - 1)
    return fortunes[num]


def fortunetelling():
    num = random.randint(0, len(responses) - 1)
    tarot_num = random.randint(0, len(tarot_names) - 1)
    tarot_response = tarot_names[tarot_num]
    return responses[num] + "\n\nI drew " + tarot_response + ". " + tarot[tarot_response]
